### ISSUE TITLE
Can't install via Package Manager using git URL

### ISSUE THREAD

**Issue by OranBar** [SolidAlloy/GenericUnityObjects#15]
![image](https://user-images.githubusercontent.com/10764350/129480556-83dc277b-0899-4a19-ad4b-0e8d628b8da7.png)

I tried following the readme to install the package from the package manager.
The first 2 packages (https://github.com/SolidAlloy/SolidUtilities.git, https://github.com/SolidAlloy/ClassTypeReference-for-Unity.git) are imported alright, but when I try to import https://github.com/SolidAlloy/GenericUnityObjects.git, I get the error shown in the image.

I should also mention that the method via modifying the manifest.json doesn't work. It looks like the version number ( "com.solidalloy.generic-unity-objects": "1.1.5") is not correct.

I think the problem is realted to cysharp, but unsure on how to proceed

I'm using Unity 2020.3.1f11

**Comment by OranBar** [comment]
I'm sorry, I realized I missed the .NET 4.x requirement. 
But now that I set it correctly, I get a different error regarding a dependency package (com.cysharp.unitask@2.2.5)

![image](https://user-images.githubusercontent.com/10764350/129724913-403acdcb-4a0c-4056-b7df-faf2bc994f02.png)

**Comment by SolidAlloy** [comment]
Hello, thanks for reporting the issue. I removed a dependency on _com.cysharp.unitask_ in the new version of the package - [2.6.0](https://github.com/SolidAlloy/GenericUnityObjects/releases/tag/2.6.0). Could you try installing it again? You might need to reimport the other two packages because they were also updated.
