### ISSUE TITLE
Warning when creating generic scriptable object

### ISSUE THREAD

**Issue by shyam-tilt** [SolidAlloy/GenericUnityObjects#20]
Hi,

I am getting the following warning when creating a generic scriptable object.
"The associated script that contains the generic type could not be found. Please check that its file name matches the class name."
![image](https://user-images.githubusercontent.com/32861775/134200694-1d560b18-537d-4816-8da0-50e1c84fd279.png)

The variables of the class are loaded in the inspector. Should this warning be ignored?

**Comment by SolidAlloy** [comment]
Hi, this happens when the script associated with the GenericScriptableObject class is not named properly. You can read about the proper naming here https://github.com/SolidAlloy/GenericUnityObjects#file-naming

I don't force the naming, so you can use the scriptable object with the warning. But should the class name change, the plugin will not be able to detect this change and the references will break.

Once you apply the proper naming to the script file, the warning will disappear and you will see the file name in the Script field instead of ConcreteClass_...

**Comment by shyam-tilt** [comment]
Thanks for pointing this out. On checking, I found that the file name and class name were the same. But the generic scriptable object class had another non monobehaviour class. Removing and placing it in its own dedicated file removed the warning.

**Comment by SolidAlloy** [comment]
Thanks for the information! Was the non-MonoBehaviour class first or second in order inside the script? I will investigate and fix this behavior. Didn't know it could cause an issue

**Comment by SolidAlloy** [comment]
I've applied a fix for cases when there are multiple classes in one script. Could you update the package and check if the warning is absent with your original situation when you had a non-MonoBehaviour class in the script?

**Comment by shyam-tilt** [comment]
The non-MonoBehaviour class was first in order inside the script. 
But after updating to the latest version I am getting the following error in the editor. This occurs when I select any script in the editor.

![image](https://user-images.githubusercontent.com/32861775/134808736-737fa011-94e4-4adf-b2f7-34eeec7c8bd2.png)

![image](https://user-images.githubusercontent.com/32861775/134809051-6346c90d-b0e9-4283-95e7-686e0bcda3d3.png)

**Comment by SolidAlloy** [comment]
Thanks, I overlooked this error. It's been fixed in the [2.10.2](https://github.com/SolidAlloy/GenericUnityObjects/releases/tag/2.10.2) version now, please check it
