### ISSUE TITLE
Error when trying to select a function in a UnityEvent

### ISSUE THREAD

**Issue by JingHaoYao** [SolidAlloy/GenericUnityObjects#23]
MissingMethodException: void UnityEditorInternal.UnityEventDrawer.GeneratePopUpForType(UnityEditor.GenericMenu,UnityEngine.Object,string,UnityEditor.SerializedProperty,System.Type[])
GenericUnityObjects.UnityEditorInternals.GenericUnityEventDrawer.DrawEvent (UnityEngine.Rect rect, System.Int32 index, System.Boolean isActive, System.Boolean isFocused) (at <49665e11fe5f425daf988d5bb98be237>:0)
UnityEditorInternal.ReorderableList.DoListElements (UnityEngine.Rect listRect, UnityEngine.Rect visibleRect) (at <ef3b6bf002d8435a97b4e938f6c49b02>:0)
UnityEditorInternal.ReorderableList.DoList (UnityEngine.Rect rect, UnityEngine.Rect visibleRect) (at <ef3b6bf002d8435a97b4e938f6c49b02>:0)
UnityEditorInternal.ReorderableList.DoList (UnityEngine.Rect rect) (at <ef3b6bf002d8435a97b4e938f6c49b02>:0)
UnityEditorInternal.UnityEventDrawer.OnGUI (UnityEngine.Rect position) (at <ef3b6bf002d8435a97b4e938f6c49b02>:0)
UnityEditorInternal.UnityEventDrawer.OnGUI (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at <ef3b6bf002d8435a97b4e938f6c49b02>:0)
UnityEditor.PropertyDrawer.OnGUISafe (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at <ef3b6bf002d8435a97b4e938f6c49b02>:0)
UnityEditor.PropertyHandler.OnGUI (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren, UnityEngine.Rect visibleArea) (at <ef3b6bf002d8435a97b4e938f6c49b02>:0)
UnityEditor.PropertyHandler.OnGUI (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren) (at <ef3b6bf002d8435a97b4e938f6c49b02>:0)
UnityEditor.PropertyHandler.OnGUILayout (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren, UnityEngine.GUILayoutOption[] options) (at <ef3b6bf002d8435a97b4e938f6c49b02>:0)
UnityEditor.EditorGUILayout.PropertyField (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren, UnityEngine.GUILayoutOption[] options) (at <ef3b6bf002d8435a97b4e938f6c49b02>:0)
UnityEditor.EditorGUILayout.PropertyField (UnityEditor.SerializedProperty property, System.Boolean includeChildren, UnityEngine.GUILayoutOption[] options) (at <ef3b6bf002d8435a97b4e938f6c49b02>:0)
GenericUnityObjects.Editor.GenericUnityObjectEditor.OnInspectorGUI () (at Library/PackageCache/com.solidalloy.generic-unity-objects@c1ec42ed89/Editor/Drawers/GenericUnityObjectEditor.cs:59)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass59_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <31768fe99cfe4466aa4a401169fb2ce5>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

This happens when I try to select a function in the inspector: 
![image](https://user-images.githubusercontent.com/23221908/136486574-609e3289-c11d-40c0-a799-85096dacc1f1.png)

**Comment by SolidAlloy** [comment]
Hi, what's the Unity version you are using? I checked it in 2021.1.22 and 2020.3.19 and didn't encounter the exception there.

**Comment by JingHaoYao** [comment]
Hi, I'm using Unity 2020.3.16f1 (EDIT: I ended up updating to unity 2021.1.23 and it worked, although I'm getting these errors in the inspector now when I click on my script files, is there a recommended version to use for this plugin? 
![image](https://user-images.githubusercontent.com/23221908/137215730-9ff7ab7d-9155-4cbc-be0c-147ab110b4ba.png)
)

**Comment by SolidAlloy** [comment]
Hi, sorry you've been facing a lot of errors recently. I fixed the `GeneratePopUpForType()` method, so the error won't appear again should you revert to 2020.3.16. 

The plugin relies on calling some internal methods, and Unity tends to change their signatures quite often, so the `MissingMethod` exceptions occur from time to time, and I try resolving them as quickly as possible. Unfortunately, I cannot fully strip the use of internal methods because some parts of Unity are completely inaccessible for implementing some of the features in the plugin.

As for the latter exception you reported, it looks like the version mismatch between GenericUnityObjects and SolidUtilities. Do you install/update GenericUnityObjects through OpenUPM? I recommend OpenUPM so that you don't have a possibility of a version mismatch. Please try installing GenericUnityObjects [2.11.1](https://github.com/SolidAlloy/GenericUnityObjects/releases/tag/2.11.1) through OpenUPM or if you update it manually, verify that you have the following versions of dependencies:
- SolidUtilities - 1.33.0
- TypeReferences - 2.11.1
