### ISSUE TITLE
Versioning error on Unity 2020.3

### ISSUE THREAD

**Issue by NeedsLoomis** [SolidAlloy/GenericUnityObjects#26]
Fresh project on Unity 2020.3.24fi with fresh install of GenericUnityObjects via openupm.

Error as follows:
Assembly 'Packages/org.nuget.system.memory/System.Memory.dll' will not be loaded due to errors:
System.Memory references strong named System.Runtime.CompilerServices.Unsafe Assembly references: 4.0.4.1 Found in project: 5.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"
System.Memory references strong named System.Buffers Assembly references: 4.0.2.0 Found in project: 4.0.3.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

**Comment by SolidAlloy** [comment]
Hello, thanks for reporting the issue. I searched for a solution that won't require you to disable the "Assembly Version Validation" option manually, but unfortunately it isn't possible. [This issue](https://github.com/xoofx/UnityNuGet/issues/29) contains more details on the topic.

I added an instruction to README so that users disable this option in Player settings before installing the package. Hopefully, it will lead to less confusion during the installation process.
