### ISSUE TITLE
uNode incompatibility

### ISSUE THREAD

**Issue by NeedsLoomis** [SolidAlloy/GenericUnityObjects#30]
The Unity plugin uNode, an FSM/Behaviour Tree/ Visual Scripting tool that generates C# code, tries to reference GenericUnityObjects by their ConcreteClasses, throwing missing assembly errors.  I figured turning on auto referencing would fix the problem, but it turns out that ConcreteClasses are internal, so now it throws inaccessible errors.

![image](https://user-images.githubusercontent.com/87632315/152619457-0ba08c0a-aab4-4657-adc3-d315f107fa6f.png)

**Comment by SolidAlloy** [comment]
Hi, thanks for submitting the issue. I make those concrete classes internal because they are not supposed to be referenced directly in code, but Unity is able to access them regardless of their visibility. I'll create an option to generate those classes as public.

As for the auto-referenced option, it is an important part of the plugin. It is disabled so that every time a new concrete class assembly is generated or changed, no assembly definitions get recompiled. This speeds up the process of generating new concrete classes and changing existing ones, so that you wait less time when the domain reload happens. If uNode generates code that accesses a DLL, they should modify the assembly definition and reference that DLL. That would be the right thing to do and would fix potential issues with other plugins and DLLs you added manually to the project. I recommend that you submit this as a feature request or bug to the uNode developer.

While you are waiting for the features to be added, you can make the SolidUtilities package local and change the following value there from 1 to 0:
https://github.com/SolidAlloy/SolidUtilities/blob/47c03c851c7cd66185bb3d7a3bf891b76dc6ddb5/Editor/Helpers/AssemblyGeneration.cs#L47

This will enable auto-referencing in all the new assemblies and will work for you while uNode isn't fixed. But I won't add it as a feature to GenericUnityObjects because it's not the right way to resolve this issue.

**Comment by SolidAlloy** [comment]
Hi, I wanted to let you know that I changed the class visibility in the [2.16.0](https://github.com/SolidAlloy/GenericUnityObjects/releases/tag/2.16.0) version. I realized that making auto-generated classes internal is too much because I already disable the auto-referencing option on the assemblies they belong to, so no one can accidentally reference them in the code anyway.
