### ISSUE TITLE
GenericUnityEditorInternals.dll will not be loaded due to errors

### ISSUE THREAD

**Issue by thewhitewayofdelight** [SolidAlloy/GenericUnityObjects#31]
Hi there,

I just installed this package on a fresh Unity 2021.2.14f1 project. And got that error that can be cleared.
But... I can't type GenericScriptableObject on scripts.
Any idea? Maybe because I'm using MacOS?

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/87333145/156888591-7e4f5075-2620-4752-8e1a-6ff70b019e93.png">

Here is the error message
```
Assembly 'Packages/com.solidalloy.generic-unity-objects/GenericUnityEditorInternals.dll' will not be loaded due to errors:
Unable to resolve reference 'SolidUtilities.Editor'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'SolidUtilities'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'GenericUnityObjects'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
```

Thank you

**Comment by SolidAlloy** [comment]
Hi, thank you for reporting the issue. Could you check where the DLL files generated from assembly definitions are located inside your project? On Windows, they are located at /Library/ScriptAssemblies/
![image](https://user-images.githubusercontent.com/22909454/157192988-8cf5abe3-212d-4a32-8e7d-ba8ae8302831.png)
It's possible that on macOS, they are located in a different folder.

As for the GenericScriptableObject issue: the issue may appear when you reference it inside an assembly definition, but you haven't added the reference to GenericUnityObjects assembly definition in the inspector:
![image](https://user-images.githubusercontent.com/22909454/157193446-72fce911-5959-4839-9a30-78766829b6e2.png)

If you create the Generic class inside Assembly-CSharp and GenericScriptableObject cannot be found, it may be due to the issue with GenericUnityEditorInternals. Let's fix the first issue and see if it resolves the second one.

**Comment by thewhitewayofdelight** [comment]
Hi SolidAlloy, I just update the package to the newest version and didn't see this issue anymore 😆 

Kind of sus :D

I will close the issue, thank you

**Comment by SolidAlloy** [comment]
That's great. Hopefully, it will not reappear :)
